### ISSUE TITLE
AWS GPU Node Job doesn't work on "RedHat OpenShift Container Platform Cluster" from demo.redhat.com

### ISSUE THREAD

**Issue by strangiato** [redhat-na-ssa/demo-ai-gitops-catalog#74]
It looks like the demo.redhat.com team changed up the way they are deploying clusters with the "RedHat OpenShift Container Platform Cluster" 

It looks like they may have moved away from using AWS instances so the existing automation to add GPUs doesn't work anymore.  It looks like they are doing baremetal deployments maybe even on their own hardware so GPUs may not be an option on the catalog item.

Just wanted to file this here since that seems to be the new "preferred" OCP cluster option when deploying something with demo.redhat.com.

**Comment by codekow** [comment]
This is good info. I still try to use the OpenShift with AWS Open Env.

Do we need to update the links in the README.md?

**Comment by codekow** [comment]
It appears that RHDP has a new option that does not use AWS instances. For GPUs we can not use the `RedHat OpenShift Container Platform Cluster` option.

Closing issue
